FROM shammishailaj/gobuilder:0.0.5 AS builder

ARG CGO
ARG OS
ARG ARCH

RUN mkdir /go/src/{{.Name}}

WORKDIR /go/src/{{.Name}}

COPY . ./

RUN go env

#RUN echo "CGO = "$CGO
#RUN echo "OS = "$OS
#RUN echo "ARCH = "$ARCH
RUN CGO_ENABLED=$CGO GOOS=$OS GOARCH=$ARCH govvv build -pkg "{{.Name}}/internal/app/{{.Name}}/cmd" -mod vendor -a -installsuffix cgo -ldflags '-extldflags "-static"' -o ./bin/{{.Name}} ./cmd/{{.Name}}/{{.Name}}.go
RUN cp ./bin/{{.Name}} /bin/

# See: https://stackoverflow.com/a/52979541/6670698
FROM scratch AS production
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/{{.Name}}/configs /{{.Name}}/configs/
COPY --from=builder /go/src/{{.Name}}/web /{{.Name}}/web/
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /go/src/{{.Name}}/bin/{{.Name}} /{{.Name}}/{{.Name}}
WORKDIR /{{.Name}}
ENV TZ {{.DateTimeZone}}
ENTRYPOINT ["/{{.Name}}/{{.Name}}","serve"]