build:
	-docker rm {{.Name}}
	-docker rmi -f {{.Name}}:latest
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 CGO_ENABLED=0 GOOS=$(os) GOARCH=$(arch) docker compose -f ./deployments/docker-compose.yml build --no-cache {{.Name}}

run:
	# https://stackoverflow.com/a/2670143/6670698
	-docker rm {{.Name}}_dev
	-docker rmi -f {{.Name}}_dev:latest
	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 CGO_ENABLED=0 GOOS=$(os) GOARCH=$(arch) docker compose -f ./deployments/docker-compose.yml up --remove-orphans {{.Name}}-dev

cli:
	sh ./deployments/build_cli.sh GOOS=$(os) GOARCH=$(arch)

test:
	docker compose -f ./deployments/docker-compose.yml up tests

lint:
	docker compose -f ./deployments/docker-compose.yml up linter

down:
	docker compose -f ./deployments/docker-compose.yml down